-- Supabase PostgreSQL schema for thesis-check system
-- Run in Supabase SQL Editor

create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role_enum') then
    create type user_role_enum as enum ('USER', 'ADMIN');
  end if;
  if not exists (select 1 from pg_type where typname = 'paper_status_enum') then
    create type paper_status_enum as enum ('DRAFT', 'SUBMITTED', 'ARCHIVED');
  end if;
  if not exists (select 1 from pg_type where typname = 'file_type_enum') then
    create type file_type_enum as enum ('PAPER_ORIGINAL', 'PAPER_PROCESSED', 'TEMPLATE', 'RESULT_REPORT', 'OTHER');
  end if;
  if not exists (select 1 from pg_type where typname = 'template_scope_enum') then
    create type template_scope_enum as enum ('SYSTEM', 'PERSONAL');
  end if;
  if not exists (select 1 from pg_type where typname = 'rule_type_enum') then
    create type rule_type_enum as enum ('PARAGRAPH', 'FONT', 'HEADING', 'PAGE', 'TABLE', 'REFERENCE', 'CUSTOM');
  end if;
  if not exists (select 1 from pg_type where typname = 'severity_enum') then
    create type severity_enum as enum ('ERROR', 'WARNING', 'INFO');
  end if;
  if not exists (select 1 from pg_type where typname = 'task_type_enum') then
    create type task_type_enum as enum ('FORMAT_CHECK', 'FULL_CHECK');
  end if;
  if not exists (select 1 from pg_type where typname = 'task_status_enum') then
    create type task_status_enum as enum ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELED');
  end if;
  if not exists (select 1 from pg_type where typname = 'log_type_enum') then
    create type log_type_enum as enum ('LOGIN', 'LOGOUT', 'CREATE', 'UPDATE', 'DELETE', 'UPLOAD', 'DOWNLOAD', 'DETECT', 'SYSTEM', 'SECURITY');
  end if;
  if not exists (select 1 from pg_type where typname = 'log_level_enum') then
    create type log_level_enum as enum ('INFO', 'WARN', 'ERROR');
  end if;
end $$;

create table if not exists public.sys_user (
  id bigint generated by default as identity primary key,
  username varchar(64) not null unique,
  password_hash varchar(255) not null,
  role user_role_enum not null default 'USER',
  real_name varchar(64),
  email varchar(128) unique,
  phone varchar(32) unique,
  status smallint not null default 1,
  last_login_at timestamp,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  deleted_at timestamp
);

create table if not exists public.paper (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.sys_user(id),
  title varchar(255) not null,
  abstract_text text,
  keywords varchar(512),
  status paper_status_enum not null default 'DRAFT',
  current_version integer not null default 1,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  deleted_at timestamp
);

create table if not exists public.file_record (
  id bigint generated by default as identity primary key,
  uploader_id bigint not null references public.sys_user(id),
  paper_id bigint references public.paper(id) on delete set null,
  file_type file_type_enum not null default 'OTHER',
  biz_ref_type varchar(64),
  biz_ref_id bigint,
  original_name varchar(255) not null,
  stored_name varchar(255) not null unique,
  storage_path varchar(500) not null,
  file_ext varchar(20),
  mime_type varchar(128),
  file_size bigint not null default 0,
  md5 varchar(32),
  is_deleted smallint not null default 0,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table if not exists public.format_template (
  id bigint generated by default as identity primary key,
  template_name varchar(128) not null,
  description varchar(500),
  scope template_scope_enum not null default 'SYSTEM',
  version_no varchar(32) not null default 'v1.0.0',
  template_file_id bigint references public.file_record(id) on delete set null,
  creator_id bigint references public.sys_user(id),
  is_default smallint not null default 0,
  status smallint not null default 1,
  published_at timestamp,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  deleted_at timestamp
);

create unique index if not exists uk_format_template_name_version on public.format_template(template_name, version_no);

create table if not exists public.format_rule (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.format_template(id) on delete cascade,
  parent_rule_id bigint references public.format_rule(id) on delete set null,
  rule_code varchar(64) not null,
  rule_name varchar(128) not null,
  rule_type rule_type_enum not null default 'CUSTOM',
  severity severity_enum not null default 'ERROR',
  rule_config jsonb not null,
  description varchar(500),
  order_no integer not null default 0,
  enabled smallint not null default 1,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now(),
  unique(template_id, rule_code)
);

create table if not exists public.detection_task (
  id bigint generated by default as identity primary key,
  task_no varchar(64) not null unique,
  paper_id bigint not null references public.paper(id),
  submitter_id bigint not null references public.sys_user(id),
  template_id bigint not null references public.format_template(id),
  source_file_id bigint not null references public.file_record(id),
  task_type task_type_enum not null default 'FORMAT_CHECK',
  status task_status_enum not null default 'PENDING',
  priority smallint not null default 5,
  progress smallint not null default 0,
  queued_at timestamp not null default now(),
  started_at timestamp,
  finished_at timestamp,
  worker_node varchar(128),
  error_message varchar(1000),
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table if not exists public.detection_result (
  id bigint generated by default as identity primary key,
  task_id bigint not null unique references public.detection_task(id) on delete cascade,
  total_score numeric(6,2),
  pass_flag smallint not null default 0,
  error_count integer not null default 0,
  warning_count integer not null default 0,
  info_count integer not null default 0,
  hit_rule_count integer not null default 0,
  summary_json jsonb,
  detail_json jsonb,
  report_file_id bigint references public.file_record(id) on delete set null,
  completed_at timestamp,
  created_at timestamp not null default now(),
  updated_at timestamp not null default now()
);

create table if not exists public.system_log (
  id bigint generated by default as identity primary key,
  user_id bigint references public.sys_user(id) on delete set null,
  log_type log_type_enum not null default 'SYSTEM',
  module varchar(64) not null,
  action varchar(128) not null,
  target_type varchar(64),
  target_id varchar(64),
  request_id varchar(64),
  ip_address varchar(45),
  user_agent varchar(500),
  level log_level_enum not null default 'INFO',
  message varchar(1000),
  detail_json jsonb,
  created_at timestamp not null default now()
);

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_sys_user_updated_at on public.sys_user;
create trigger trg_sys_user_updated_at before update on public.sys_user for each row execute function public.update_updated_at_column();
drop trigger if exists trg_paper_updated_at on public.paper;
create trigger trg_paper_updated_at before update on public.paper for each row execute function public.update_updated_at_column();
drop trigger if exists trg_file_record_updated_at on public.file_record;
create trigger trg_file_record_updated_at before update on public.file_record for each row execute function public.update_updated_at_column();
drop trigger if exists trg_format_template_updated_at on public.format_template;
create trigger trg_format_template_updated_at before update on public.format_template for each row execute function public.update_updated_at_column();
drop trigger if exists trg_format_rule_updated_at on public.format_rule;
create trigger trg_format_rule_updated_at before update on public.format_rule for each row execute function public.update_updated_at_column();
drop trigger if exists trg_detection_task_updated_at on public.detection_task;
create trigger trg_detection_task_updated_at before update on public.detection_task for each row execute function public.update_updated_at_column();
drop trigger if exists trg_detection_result_updated_at on public.detection_result;
create trigger trg_detection_result_updated_at before update on public.detection_result for each row execute function public.update_updated_at_column();

-- Basic RLS (demo): authenticated users can read; admins can write.
alter table public.sys_user enable row level security;
alter table public.paper enable row level security;
alter table public.file_record enable row level security;
alter table public.format_template enable row level security;
alter table public.format_rule enable row level security;
alter table public.detection_task enable row level security;
alter table public.detection_result enable row level security;
alter table public.system_log enable row level security;

drop policy if exists "read all users" on public.sys_user;
create policy "read all users" on public.sys_user for select using (true);
drop policy if exists "write users for all" on public.sys_user;
create policy "write users for all" on public.sys_user for all using (true) with check (true);

drop policy if exists "read all paper" on public.paper;
create policy "read all paper" on public.paper for select using (true);
drop policy if exists "write paper for all" on public.paper;
create policy "write paper for all" on public.paper for all using (true) with check (true);

drop policy if exists "read all file_record" on public.file_record;
create policy "read all file_record" on public.file_record for select using (true);
drop policy if exists "write file_record for all" on public.file_record;
create policy "write file_record for all" on public.file_record for all using (true) with check (true);

drop policy if exists "read all format_template" on public.format_template;
create policy "read all format_template" on public.format_template for select using (true);
drop policy if exists "write format_template for all" on public.format_template;
create policy "write format_template for all" on public.format_template for all using (true) with check (true);

drop policy if exists "read all format_rule" on public.format_rule;
create policy "read all format_rule" on public.format_rule for select using (true);
drop policy if exists "write format_rule for all" on public.format_rule;
create policy "write format_rule for all" on public.format_rule for all using (true) with check (true);

drop policy if exists "read all detection_task" on public.detection_task;
create policy "read all detection_task" on public.detection_task for select using (true);
drop policy if exists "write detection_task for all" on public.detection_task;
create policy "write detection_task for all" on public.detection_task for all using (true) with check (true);

drop policy if exists "read all detection_result" on public.detection_result;
create policy "read all detection_result" on public.detection_result for select using (true);
drop policy if exists "write detection_result for all" on public.detection_result;
create policy "write detection_result for all" on public.detection_result for all using (true) with check (true);

drop policy if exists "read all system_log" on public.system_log;
create policy "read all system_log" on public.system_log for select using (true);
drop policy if exists "write system_log for all" on public.system_log;
create policy "write system_log for all" on public.system_log for all using (true) with check (true);

